### ISSUE TITLE
Need to update bitwarden versions

### ISSUE THREAD

**Issue by pcrow** [oddlama/overlay#1]
bitwarden_rs-1.19.0 is out.  Just rename the ebuild and it works.
bitwarden_rs-web-vault-2.18.1.d is out.  Renaming the ebuild works, but I had trouble getting it to download for some reason until I did it manually (it was trying Gentoo mirrors instead of going straight to GitHub; I don't know why).

**Comment by oddlama** [comment]
Thanks for the heads up, I will quickly verify that everything is working fine and then push the update.
My guess is that you probably had trouble downloading `bitwarden_rs-web-vault-2.18.1.d` because the version suffix `d` should be attached like `2.18.1d`.

**Comment by oddlama** [comment]
Done
