### ISSUE TITLE
Add a License

### ISSUE THREAD

**Issue by Retidurc** [oddlama/overlay#3]
Hello! I think you should add a licence to your overlay. Otherwise you risk to have the [problem described in the licence chooser](https://choosealicense.com/no-permission/  ) if people décide to contribue to the overlay. 
I' don't think it's a major problem, but better be safe.

Have a good day !

**Comment by oddlama** [comment]
All of the ebuilds do have a license statement at the top. :)

**Comment by oddlama** [comment]
I'll add a global statement so it is easier to see. (I think most ebuilds are GPL-2 due to copy-paste from gentoo repositories)

**Comment by Retidurc** [comment]
I was worried about all the misc files like metadata or manifest. That may be a little paranoid on my part but just wanted everything to be super neat and clear, as I'll may start using your overlay to provide bitwarden host in a pro environement. And I wanted to be able to contribute without causing any problems.

**Comment by oddlama** [comment]
Ah I see, those are mostly generated or wouldn't fall under any copyright (generally available information), but you are right that it would be better to have a global statement.

**Comment by oddlama** [comment]
Oh and as you mentioned you might use this to deploy vaultwarden: I feel obliged to tell you that I am absolutely only maintaining this for my personal servers. So I cannot give any guarantees that I will be able to provide "instant" updates as soon as they get available. But of course I'm open to PRs in case you notice any problems! :D

**Comment by Retidurc** [comment]
I am well aware, that's why I wanted to be able to contribute back, or be able to fork the whole overlay if you ever cease to maintain it, without causing problems :D ! 

Thanks !
